/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypeSettingsRouteImport } from './routes/prototype.settings'
import { Route as PrototypePagesRouteImport } from './routes/prototype.pages'
import { Route as PrototypeMediaRouteImport } from './routes/prototype.media'
import { Route as PrototypeGalleryRouteImport } from './routes/prototype.gallery'
import { Route as PrototypeDesignSystemRouteImport } from './routes/prototype.design-system'
import { Route as PrototypeDashboardRouteImport } from './routes/prototype.dashboard'
import { Route as PrototypePagesEditRouteImport } from './routes/prototype.pages.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeSettingsRoute = PrototypeSettingsRouteImport.update({
  id: '/prototype/settings',
  path: '/prototype/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypePagesRoute = PrototypePagesRouteImport.update({
  id: '/prototype/pages',
  path: '/prototype/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeMediaRoute = PrototypeMediaRouteImport.update({
  id: '/prototype/media',
  path: '/prototype/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeGalleryRoute = PrototypeGalleryRouteImport.update({
  id: '/prototype/gallery',
  path: '/prototype/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeDesignSystemRoute = PrototypeDesignSystemRouteImport.update({
  id: '/prototype/design-system',
  path: '/prototype/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeDashboardRoute = PrototypeDashboardRouteImport.update({
  id: '/prototype/dashboard',
  path: '/prototype/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypePagesEditRoute = PrototypePagesEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PrototypePagesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/prototype/dashboard': typeof PrototypeDashboardRoute
  '/prototype/design-system': typeof PrototypeDesignSystemRoute
  '/prototype/gallery': typeof PrototypeGalleryRoute
  '/prototype/media': typeof PrototypeMediaRoute
  '/prototype/pages': typeof PrototypePagesRouteWithChildren
  '/prototype/settings': typeof PrototypeSettingsRoute
  '/prototype/pages/edit': typeof PrototypePagesEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/prototype/dashboard': typeof PrototypeDashboardRoute
  '/prototype/design-system': typeof PrototypeDesignSystemRoute
  '/prototype/gallery': typeof PrototypeGalleryRoute
  '/prototype/media': typeof PrototypeMediaRoute
  '/prototype/pages': typeof PrototypePagesRouteWithChildren
  '/prototype/settings': typeof PrototypeSettingsRoute
  '/prototype/pages/edit': typeof PrototypePagesEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/prototype/dashboard': typeof PrototypeDashboardRoute
  '/prototype/design-system': typeof PrototypeDesignSystemRoute
  '/prototype/gallery': typeof PrototypeGalleryRoute
  '/prototype/media': typeof PrototypeMediaRoute
  '/prototype/pages': typeof PrototypePagesRouteWithChildren
  '/prototype/settings': typeof PrototypeSettingsRoute
  '/prototype/pages/edit': typeof PrototypePagesEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/prototype/dashboard'
    | '/prototype/design-system'
    | '/prototype/gallery'
    | '/prototype/media'
    | '/prototype/pages'
    | '/prototype/settings'
    | '/prototype/pages/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/prototype/dashboard'
    | '/prototype/design-system'
    | '/prototype/gallery'
    | '/prototype/media'
    | '/prototype/pages'
    | '/prototype/settings'
    | '/prototype/pages/edit'
  id:
    | '__root__'
    | '/'
    | '/prototype/dashboard'
    | '/prototype/design-system'
    | '/prototype/gallery'
    | '/prototype/media'
    | '/prototype/pages'
    | '/prototype/settings'
    | '/prototype/pages/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrototypeDashboardRoute: typeof PrototypeDashboardRoute
  PrototypeDesignSystemRoute: typeof PrototypeDesignSystemRoute
  PrototypeGalleryRoute: typeof PrototypeGalleryRoute
  PrototypeMediaRoute: typeof PrototypeMediaRoute
  PrototypePagesRoute: typeof PrototypePagesRouteWithChildren
  PrototypeSettingsRoute: typeof PrototypeSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/settings': {
      id: '/prototype/settings'
      path: '/prototype/settings'
      fullPath: '/prototype/settings'
      preLoaderRoute: typeof PrototypeSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/pages': {
      id: '/prototype/pages'
      path: '/prototype/pages'
      fullPath: '/prototype/pages'
      preLoaderRoute: typeof PrototypePagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/media': {
      id: '/prototype/media'
      path: '/prototype/media'
      fullPath: '/prototype/media'
      preLoaderRoute: typeof PrototypeMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/gallery': {
      id: '/prototype/gallery'
      path: '/prototype/gallery'
      fullPath: '/prototype/gallery'
      preLoaderRoute: typeof PrototypeGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/design-system': {
      id: '/prototype/design-system'
      path: '/prototype/design-system'
      fullPath: '/prototype/design-system'
      preLoaderRoute: typeof PrototypeDesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/dashboard': {
      id: '/prototype/dashboard'
      path: '/prototype/dashboard'
      fullPath: '/prototype/dashboard'
      preLoaderRoute: typeof PrototypeDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/pages/edit': {
      id: '/prototype/pages/edit'
      path: '/edit'
      fullPath: '/prototype/pages/edit'
      preLoaderRoute: typeof PrototypePagesEditRouteImport
      parentRoute: typeof PrototypePagesRoute
    }
  }
}

interface PrototypePagesRouteChildren {
  PrototypePagesEditRoute: typeof PrototypePagesEditRoute
}

const PrototypePagesRouteChildren: PrototypePagesRouteChildren = {
  PrototypePagesEditRoute: PrototypePagesEditRoute,
}

const PrototypePagesRouteWithChildren = PrototypePagesRoute._addFileChildren(
  PrototypePagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrototypeDashboardRoute: PrototypeDashboardRoute,
  PrototypeDesignSystemRoute: PrototypeDesignSystemRoute,
  PrototypeGalleryRoute: PrototypeGalleryRoute,
  PrototypeMediaRoute: PrototypeMediaRoute,
  PrototypePagesRoute: PrototypePagesRouteWithChildren,
  PrototypeSettingsRoute: PrototypeSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
